#
# SPDX-License-Identifier: Apache-2.0
#

repository:
  name: documentation
  description: PQCP Documentation
  homepage: https://docs.pqcodepackage.org/latest/
  default_branch: main
  has_downloads: false
  has_issues: true
  has_projects: true
  has_wiki: false
  archived: false
  private: false
  allow_squash_merge: true
  allow_merge_commit: false
  allow_rebase_merge: true
