#
# SPDX-License-Identifier: Apache-2.0
#
blank_issues_enabled: false
contact_links:
  - name: Support Request
    url: https://discord.com/invite/xyVnwzfg5R
    about: Support request or question relating to pqca Docs